version: '3'
services:
  db:
      image: mysql:8.0
      ports:
        - "30000:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - './data:/var/lib/mysql'

  app:
    container_name: flask-app
    build: ./app
    ports:
      - "8000:8000"
    networks:
      - flask
   
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: abc123
      DB_NAME: challenge

networks:
  flask:
    driver: bridge
