version: '3'
services:
  app:
    container_name:flask-app
    build: ./app
    ports:
      - "8000:8000"
    networks:
      - flask
    depend_on:
      - db
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: abc123
      DB_NAME: challenge

  db:
      image: mysql:8.0.21
      ports:
        - "30000:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - './data:/var/lib/mysql'


networks:
  flask:
    driver: bridge
